=== sandysams0n/ESE1/EMS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xs:element name="Company">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="Employee">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Emp-ID" type="xs:integer" />
            <xs:element name="Emp-name" type="xs:string"/>
            <xs:element name="Emp-age" type="xs:integer"/>
            <xs:element name="Emp-salary" type="xs:integer"/>
            <xs:element name="Emp-emailId" type="xs:string"/>
            <xs:element name="Emp-phonenum" type="xs:integer"/>
            <xs:element name="Emp-Designation" type="xs:string"/>  
            <xs:element name="Emp-promotion" type="xs:string"/>
              
		     </xs:sequence>
		   </xs:complexType>
		</xs:element>
     </xs:sequence>
    </xs:complexType>
   </xs:element> 
</xs:schema>

=== sandysams0n/ESE1/EMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="EMS.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="EMS.xsd">
 
 <Employee>
 		<Emp-ID>202001</Emp-ID>
 		<Emp-name>Laura Bailey</Emp-name>
 		<Emp-age>29</Emp-age>
 		<Emp-salary>70,000</Emp-salary>
 		<Emp-emailId>laura@gmail.com</Emp-emailId>
 		<Emp-phonenum>2345433287</Emp-phonenum>
 		<Emp-Designation>Assistant Manager</Emp-Designation>
 		<Emp-promotion>Developer</Emp-promotion>
 		
 </Employee>
 
 <Employee>
 		<Emp-ID>202002</Emp-ID>
 		<Emp-name>Brad</Emp-name>
 		<Emp-age>39</Emp-age>
 		<Emp-salary>90,000</Emp-salary>
 		<Emp-emailId>brad@gmail.com</Emp-emailId>
 		<Emp-phonenum>7856907834</Emp-phonenum>
 		<Emp-Designation>Systems Architect</Emp-Designation>
 		<Emp-promotion>Developer</Emp-promotion>
 </Employee>
 
 <Employee>
 		<Emp-ID>202003</Emp-ID>
 		<Emp-name>Eric</Emp-name>
 		<Emp-age>52</Emp-age>
 		<Emp-salary>95,000</Emp-salary>
 		<Emp-emailId>eric.e@a.com</Emp-emailId>
 		<Emp-phonenum>1278563498</Emp-phonenum>
 		<Emp-Designation>Financial Analyst</Emp-Designation>
 		<Emp-promotion>Associate Project Manager</Emp-promotion>
 </Employee>
 
 <Employee>
 		<Emp-ID>202004</Emp-ID>
 		<Emp-name>Andrew</Emp-name>
 		<Emp-age>42</Emp-age>
 		<Emp-salary>85,000</Emp-salary>
 		<Emp-emailId>drew@a.com</Emp-emailId>
 		<Emp-phonenum>6534981092</Emp-phonenum>
 		<Emp-Designation>Senior Analyst</Emp-Designation>
 		<Emp-promotion>Team Leader</Emp-promotion>
 </Employee>
 
 <Employee>
 		<Emp-ID>202005</Emp-ID>
 		<Emp-name>Michael</Emp-name>
 		<Emp-age>37</Emp-age>
 		<Emp-salary>60,000</Emp-salary>
 		<Emp-emailId>mic.t@a.com</Emp-emailId>
 		<Emp-phonenum>2176340977</Emp-phonenum>
 		<Emp-Designation>Associate Consultant</Emp-Designation>
 		<Emp-promotion>Developer</Emp-promotion>
 </Employee>
 </Company>
